server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.1.245:3306/mytest?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123@jkcq.COM
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximumPoolSize: 20
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 20000
      maxLifetime: 1800000
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    database-platform: MYSQL
