spring:
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: cn.classyex.menu.application.LocalMysqlDialect
    database-platform: MYSQL

